export const HELP_STORAGE_KEY = 'mlb-dashboard-help-v1';

export const helpItems = [
  {
    id: 'global-main-nav',
    area: 'global',
    mode: null,
    target: '[data-help-id="global-main-nav"]',
    title: 'Main Navigation',
    summary: 'The dashboard is organized into four main areas.',
    body: 'Use Production for job management, Bottlenecks for stuck work, Sales for sales performance, and TV Wallboard for the big-screen display. The app is one shared job system with different views of the same records.',
    manualEquivalent: "The office's Critical Path Book, whiteboard, sales tracking sheets, and meeting discussions.",
    whyItMatters: 'It keeps the dashboard organized around the way MLB already reviews work.',
    whatToDo: 'Choose the area that matches the conversation or task you are working on.',
    tour: 'full-dashboard',
    order: 10,
  },
  {
    id: 'global-region-filter',
    area: 'global',
    mode: null,
    target: '[data-help-id="global-region-filter"]',
    title: 'Region Filter',
    summary: 'Filter the dashboard by location.',
    body: 'Use this to view All work or narrow the dashboard to Virginia or Carolina. This affects production, bottlenecks, sales, and wallboard views.',
    manualEquivalent: 'Separate location boards or location-specific review conversations.',
    whyItMatters: 'It keeps regional production and sales conversations focused.',
    whatToDo: 'Choose All, Virginia, or Carolina before reviewing the current screen.',
    tour: 'full-dashboard',
    order: 20,
  },
  {
    id: 'global-period-filter',
    area: 'global',
    mode: null,
    target: '[data-help-id="global-period-filter"]',
    title: 'Period Filter',
    summary: 'Filter by time period.',
    body: 'Use MTD, QTD, YTD, or All to adjust which sold jobs and sales numbers are included.',
    manualEquivalent: 'Monthly, quarterly, and year-to-date sales and production review.',
    whyItMatters: 'It keeps reports and pipeline views aligned to the review period.',
    whatToDo: 'Set the period before comparing sales totals or active work.',
    tour: 'full-dashboard',
    order: 30,
  },
  {
    id: 'global-new-project',
    area: 'global',
    mode: null,
    target: '[data-help-id="global-new-project"]',
    title: 'New Project',
    summary: 'Start a new digital job record.',
    body: 'Use New Project when a contract has been received and the job needs to be entered into the dashboard. The project file can include customer details, scopes, dates, financials, permits, notes, and cancellation information.',
    manualEquivalent: 'Creating a physical job file and adding a job to the Critical Path Book.',
    whyItMatters: 'All dashboard views depend on the project file being complete.',
    whatToDo: 'Create the project, then add each scope and production date as work moves forward.',
    tour: 'full-dashboard',
    order: 40,
  },
  {
    id: 'global-admin-menu',
    area: 'global',
    mode: null,
    target: '[data-help-id="global-admin-menu"]',
    title: 'Admin Tools and Help Center',
    summary: 'Backup, reset, and help tools live here.',
    body: 'The user menu keeps data utilities and help actions out of the main workflow. Open it to access backup JSON tools, reset demo data, the Help Center, help icon mode, and walkthroughs.',
    manualEquivalent: 'Office admin binder and onboarding notes.',
    whyItMatters: 'Leadership and operators can use help only when they need it.',
    whatToDo: 'Open this menu to launch help or manage local demo data.',
    tour: 'full-dashboard',
    order: 190,
  },
  {
    id: 'production-main-nav',
    area: 'production',
    mode: 'customer',
    target: '[data-help-id="global-main-nav"]',
    title: 'Production',
    summary: 'The main job management area.',
    body: 'Production contains three ways to look at the same production data: Customer, Book, and Meeting. Customer groups work by customer file. Book shows the critical path ledger. Meeting focuses the weekly critical path conversation.',
    manualEquivalent: 'Customer folder, Critical Path Book, and weekly critical path meeting.',
    whyItMatters: 'Production is where active job records are reviewed and edited.',
    whatToDo: 'Use Customer, Book, or Meeting depending on the production conversation.',
    tour: 'full-dashboard',
    order: 50,
  },
  {
    id: 'production-subnav',
    area: 'production',
    mode: null,
    target: '[data-help-id="production-subnav"]',
    title: 'Production Views',
    summary: 'Three views of the same production records.',
    body: 'Customer, Book, and Meeting are not separate datasets. They are different perspectives on the same project files and scopes.',
    manualEquivalent: 'Switching between the customer folder, the book, and the weekly agenda.',
    whyItMatters: 'Updates in one view are reflected everywhere else.',
    whatToDo: 'Choose the view that best fits the current task.',
    tour: 'production',
    order: 100,
  },
  {
    id: 'production-customer-mode',
    area: 'production',
    mode: 'customer',
    target: '[data-help-id="production-customer-mode"]',
    title: 'Customer View',
    summary: 'Group all scopes under the customer.',
    body: 'Customer View keeps multiple scopes under one customer record. This prevents the same customer from being scattered across the board when they have roof, siding, windows, gutters, trim, or other work scopes.',
    manualEquivalent: 'Customer/job folder plus notes from the book and board.',
    whyItMatters: 'It makes the whole customer file easy to review before editing.',
    whatToDo: 'Open a file to update customer details, scopes, finances, permits, and notes.',
    tour: 'production',
    order: 110,
  },
  {
    id: 'production-book-mode',
    area: 'production',
    mode: 'book',
    target: '[data-help-id="production-book-mode"]',
    title: 'Book View',
    summary: 'The digital Critical Path Book.',
    body: 'Book View is the closest replacement for the paper production ledger. Each row represents a job scope and shows dates such as Date Sold, Measure Requested, Measure Date, Order Date, Material ETA, Materials In, Scheduled, Completion, and Collected.',
    manualEquivalent: 'Paper Critical Path Book.',
    whyItMatters: 'It gives the book workflow a searchable, editable digital version.',
    whatToDo: 'Scan rows for missing dates or alerts, then use Open File to update the project.',
    tour: 'production',
    order: 120,
  },
  {
    id: 'production-meeting-mode',
    area: 'production',
    mode: 'meeting',
    target: '[data-help-id="production-meeting-mode"]',
    title: 'Meeting View',
    summary: 'Weekly critical path meeting agenda.',
    body: 'Meeting View strips the production data down to what is needed for the weekly conversation: project/scopes, value, current status, next action, and decision needed.',
    manualEquivalent: 'Hannah and Jimmy reviewing the Critical Path Book together.',
    whyItMatters: 'It keeps the meeting focused on decisions and next actions.',
    whatToDo: 'Review the current status and decision needed columns during the weekly sync.',
    tour: 'production',
    order: 130,
  },
  {
    id: 'customer-project-card',
    area: 'production',
    mode: 'customer',
    target: '[data-help-id="customer-project-card"]',
    title: 'Customer Project Card',
    summary: 'One customer file with all scopes underneath.',
    body: 'Each card summarizes the customer, current total, active date, alerts, and work scopes. Expanding the card shows the scope-level next actions.',
    manualEquivalent: 'A physical customer file with book and board notes attached.',
    whyItMatters: 'It prevents work scopes for the same customer from being reviewed in isolation.',
    whatToDo: 'Expand the card to review scopes or open the file to edit details.',
    tour: 'production',
    order: 140,
  },
  {
    id: 'customer-scope-card',
    area: 'production',
    mode: 'customer',
    target: '[data-help-id="customer-scope-card"]',
    title: 'Scope Card',
    summary: 'One trade or product under the customer.',
    body: 'A scope is a specific type of work such as roof, siding, windows, gutters, trim, decks, doors, repairs, or miscellaneous work. Each scope has its own measurement, material, schedule, crew, completion, notes, and specs.',
    manualEquivalent: 'Separate lines or notes for each type of work under the same customer.',
    whyItMatters: 'Scope dates drive bottlenecks, the book, and the wallboard.',
    whatToDo: 'Review the next action and date badges for each scope.',
    tour: 'production',
    order: 150,
  },
  {
    id: 'customer-open-file',
    area: 'production',
    mode: 'customer',
    target: '[data-help-id="customer-open-file"]',
    title: 'Open File',
    summary: 'Open the editable project record.',
    body: 'Open File launches the project modal. This is where the customer record, intake checklist, scopes, financials, permits, notes, and cancellation details are updated.',
    manualEquivalent: 'Opening the physical customer/job folder.',
    whyItMatters: 'All dashboard views update from this record.',
    whatToDo: 'Use it whenever a date, scope, financial detail, or note needs to change.',
    tour: 'production',
    order: 160,
  },
  {
    id: 'book-view-header',
    area: 'production',
    mode: 'book',
    target: '[data-help-id="book-view-header"]',
    title: 'Book View',
    summary: 'The digital Critical Path Book.',
    body: 'Book View is a one-row-per-scope production ledger. It is designed for scanning production dates and finding rows that need updates.',
    manualEquivalent: 'Paper Critical Path Book.',
    whyItMatters: 'It preserves the familiar book workflow while making records editable.',
    whatToDo: 'Scan missing dates and use Open File when a row needs correction.',
    tour: 'full-dashboard',
    order: 70,
  },
  {
    id: 'book-status-key',
    area: 'production',
    mode: 'book',
    target: '[data-help-id="book-status-key"]',
    title: 'Status Key',
    summary: 'Color-coded dates and statuses.',
    body: 'The status key helps users quickly identify important production dates and stuck items. Measure Date, Order Date, Material ETA, Materials In, Scheduled, and urgent/stuck alerts use consistent badges across the dashboard.',
    manualEquivalent: 'The color/status language from the physical whiteboard.',
    whyItMatters: 'Consistent color language makes scanning faster.',
    whatToDo: 'Use the key to interpret date badges and urgent rows.',
    tour: 'production',
    order: 170,
  },
  {
    id: 'book-open-file',
    area: 'production',
    mode: 'book',
    target: '[data-help-id="book-open-file"]',
    title: 'Open File from Book',
    summary: 'Edit the job record directly from the book.',
    body: 'Use Open File when you find a row that needs an update. This prevents extra navigation back to Customer View and keeps the book workflow efficient.',
    manualEquivalent: 'Finding a job in the book and then updating the file or notes.',
    whyItMatters: 'It keeps the book review from turning into a navigation task.',
    whatToDo: 'Click Open File on the row that needs an update.',
    tour: 'full-dashboard',
    order: 80,
  },
  {
    id: 'book-export-csv',
    area: 'production',
    mode: 'book',
    target: '[data-help-id="book-export-csv"]',
    title: 'Export CSV',
    summary: 'Export the Critical Path Book.',
    body: 'Export creates a spreadsheet-friendly copy of the current filtered book rows for offline review or sharing.',
    manualEquivalent: 'Printing or copying the book for a meeting.',
    whyItMatters: 'It gives leadership a portable version of the current book view.',
    whatToDo: 'Set filters first, then export when you need a file copy.',
    tour: 'production',
    order: 180,
  },
  {
    id: 'book-print-book',
    area: 'production',
    mode: 'book',
    target: '[data-help-id="book-print-book"]',
    title: 'Print Book',
    summary: 'Print the filtered book view.',
    body: 'Print Book creates a print-ready version of the current Critical Path Book view.',
    manualEquivalent: 'Printed production ledger for meeting review.',
    whyItMatters: 'It supports teams that still need paper during transition.',
    whatToDo: 'Set region and period, then print.',
    tour: 'production',
    order: 190,
  },
  {
    id: 'meeting-view-header',
    area: 'production',
    mode: 'meeting',
    target: '[data-help-id="meeting-view-header"]',
    title: 'Meeting View',
    summary: 'Weekly critical path meeting agenda.',
    body: 'Meeting View focuses the review on active uncompleted projects, their current status, next action, and decision needed.',
    manualEquivalent: 'Weekly Critical Path Book review.',
    whyItMatters: 'It keeps the meeting from getting buried in every field in the project file.',
    whatToDo: 'Review each row and resolve the decision needed column.',
    tour: 'full-dashboard',
    order: 90,
  },
  {
    id: 'meeting-current-status',
    area: 'production',
    mode: 'meeting',
    target: '[data-help-id="meeting-current-status"]',
    title: 'Current Status',
    summary: 'Where each scope stands now.',
    body: 'Current status shows each scope with the calculated production status and next action.',
    manualEquivalent: 'Meeting notes beside the book row.',
    whyItMatters: 'It makes the weekly review actionable.',
    whatToDo: 'Use the status and next action to assign follow-up.',
    tour: 'production',
    order: 200,
  },
  {
    id: 'meeting-next-action',
    area: 'production',
    mode: 'meeting',
    target: '[data-help-id="meeting-next-action"]',
    title: 'Next Action',
    summary: 'The next production move.',
    body: 'Next Action is calculated from the scope dates and project state so the team can see what needs to happen next.',
    manualEquivalent: 'Handwritten next step in meeting notes.',
    whyItMatters: 'It reduces ambiguity after the meeting.',
    whatToDo: 'Confirm the action owner and update the project file when complete.',
    tour: 'production',
    order: 210,
  },
  {
    id: 'meeting-decision-needed',
    area: 'production',
    mode: 'meeting',
    target: '[data-help-id="meeting-decision-needed"]',
    title: 'Decision Needed',
    summary: 'The item that needs leadership attention.',
    body: 'Decision Needed captures what must be decided before the job can move forward.',
    manualEquivalent: 'Highlighted question during the weekly book review.',
    whyItMatters: 'It keeps blockers visible until resolved.',
    whatToDo: 'Update the project file after the decision is made.',
    tour: 'production',
    order: 220,
  },
  {
    id: 'bottlenecks-main-nav',
    area: 'bottlenecks',
    mode: 'all',
    target: '[data-help-id="global-main-nav"]',
    title: 'Bottlenecks',
    summary: 'Find stuck work quickly.',
    body: 'Bottlenecks pulls forward jobs and scopes that need attention. It helps users avoid scanning the whole book or board to find late measurement, missing material lists, unscheduled work, late materials, collection issues, or decision needs.',
    manualEquivalent: 'Manually scanning the book and whiteboard for stuck jobs.',
    whyItMatters: 'It turns hidden delays into a short follow-up list.',
    whatToDo: 'Start with the oldest or highest-count bottleneck.',
    tour: 'full-dashboard',
    order: 100,
  },
  {
    id: 'bottlenecks-subnav',
    area: 'bottlenecks',
    mode: null,
    target: '[data-help-id="bottlenecks-subnav"]',
    title: 'Bottleneck Filters',
    summary: 'Switch between all bottlenecks and measurement follow-up.',
    body: 'All shows every alert group. Measurement focuses on the sold-to-measured bottleneck and material list follow-up.',
    manualEquivalent: 'Scanning the whole board or checking only measurement follow-up.',
    whyItMatters: 'Different meetings need different bottleneck focus.',
    whatToDo: 'Use All for broad review and Measurement for measurer follow-up.',
    tour: 'bottlenecks',
    order: 300,
  },
  {
    id: 'bottlenecks-all-filter',
    area: 'bottlenecks',
    mode: 'all',
    target: '[data-help-id="bottlenecks-all-filter"]',
    title: 'All Bottlenecks',
    summary: 'Review all active alert types.',
    body: 'All Bottlenecks groups stuck jobs by alert type so the team can see where production is backing up.',
    manualEquivalent: 'Scanning the whole Critical Path Book for overdue items.',
    whyItMatters: 'It shows whether delays are concentrated in measurement, ordering, scheduling, or collections.',
    whatToDo: 'Open an alert item to update the related file.',
    tour: 'bottlenecks',
    order: 310,
  },
  {
    id: 'bottlenecks-measurement-filter',
    area: 'bottlenecks',
    mode: 'measurement',
    target: '[data-help-id="bottlenecks-measurement-filter"]',
    title: 'Measurement Filter',
    summary: 'Focus on the sold-to-measured bottleneck.',
    body: 'Measurement shows work that needs measurement or a material list before materials can be ordered. This supports the goal of reducing delay between sold date, measurement, material list, and ordering.',
    manualEquivalent: 'Calling or texting measurers and checking the book to see what still needs measurement.',
    whyItMatters: 'Measurement delays create downstream material and schedule delays.',
    whatToDo: 'Follow up on the oldest request first.',
    tour: 'full-dashboard',
    order: 110,
  },
  {
    id: 'bottleneck-alert-card',
    area: 'bottlenecks',
    mode: 'all',
    target: '[data-help-id="bottleneck-alert-card"]',
    title: 'Bottleneck Alert Card',
    summary: 'A grouped list of stuck work.',
    body: 'Each card groups projects by alert type and shows how many items are stuck, the oldest item, and the average age.',
    manualEquivalent: 'Highlighting problem rows in the book.',
    whyItMatters: 'It helps leadership see where follow-up is needed most.',
    whatToDo: 'Open the project from the card to update dates or notes.',
    tour: 'bottlenecks',
    order: 320,
  },
  {
    id: 'bottleneck-days-stuck',
    area: 'bottlenecks',
    mode: 'all',
    target: '[data-help-id="bottleneck-days-stuck"]',
    title: 'Days Stuck',
    summary: 'Shows how long an item has waited.',
    body: 'Days stuck helps prioritize follow-up. Items with higher days stuck should usually be reviewed first, especially if measurement, materials, scheduling, or installation is overdue.',
    manualEquivalent: 'Remembering how long a job has been sitting in the same stage.',
    whyItMatters: 'Age makes the follow-up priority obvious.',
    whatToDo: 'Start with the highest day count.',
    tour: 'bottlenecks',
    order: 330,
  },
  {
    id: 'measurement-queue-header',
    area: 'bottlenecks',
    mode: 'measurement',
    target: '[data-help-id="measurement-queue-header"]',
    title: 'Measurement Queue',
    summary: 'Measurement and material-list follow-up.',
    body: 'The queue tracks sold scopes that still need measurement, material list, or ordering steps before production can move forward.',
    manualEquivalent: 'Measurer follow-up list.',
    whyItMatters: 'This is one of the earliest bottlenecks after a sale.',
    whatToDo: 'Review days since request and open the file to update measurement fields.',
    tour: 'bottlenecks',
    order: 340,
  },
  {
    id: 'measurement-days-since-request',
    area: 'bottlenecks',
    mode: 'measurement',
    target: '[data-help-id="measurement-days-since-request"]',
    title: 'Days Since Request',
    summary: 'How long measurement has waited.',
    body: 'This count shows the age of the measurement or material-list request. Late items are highlighted so follow-up can happen quickly.',
    manualEquivalent: 'Checking the sold date and measure request date in the book.',
    whyItMatters: 'A delayed measurement delays ordering and scheduling.',
    whatToDo: 'Follow up with the measurer or update the file if the work is complete.',
    tour: 'bottlenecks',
    order: 350,
  },
  {
    id: 'measurement-open-file',
    area: 'bottlenecks',
    mode: 'measurement',
    target: '[data-help-id="measurement-open-file"]',
    title: 'Open File',
    summary: 'Update measurement and material-list fields.',
    body: 'Open File launches the project record so the measurement, material list, order date, and notes can be updated.',
    manualEquivalent: 'Updating the customer file after measurer follow-up.',
    whyItMatters: 'The queue clears only when the project data is updated.',
    whatToDo: 'Open the file and update the scope dates.',
    tour: 'bottlenecks',
    order: 360,
  },
  {
    id: 'sales-main-nav',
    area: 'sales',
    mode: null,
    target: '[data-help-id="global-main-nav"]',
    title: 'Sales',
    summary: 'Sales performance and coaching view.',
    body: 'Sales shows revenue, projects sold, leads given, close rate, cancel rate, average contract, value per lead, and salesperson performance. This is used for management and coaching, not detailed production scheduling.',
    manualEquivalent: 'Sales spreadsheet, sales meeting notes, and manual totals.',
    whyItMatters: 'It connects sold work to revenue, leads, and cancellations.',
    whatToDo: 'Use this view for sales performance review and coaching.',
    tour: 'full-dashboard',
    order: 120,
  },
  {
    id: 'sales-summary-metrics',
    area: 'sales',
    mode: null,
    target: '[data-help-id="sales-summary-metrics"]',
    title: 'Sales Summary Metrics',
    summary: 'Top-level sales performance.',
    body: 'The summary cards show revenue, projects sold, leads given, close rate, and cancellation rate for the current region and period.',
    manualEquivalent: 'Sales spreadsheet totals.',
    whyItMatters: 'Leadership can scan the sales picture before looking at rep detail.',
    whatToDo: 'Set region and period filters before reviewing the cards.',
    tour: 'sales',
    order: 400,
  },
  {
    id: 'sales-revenue',
    area: 'sales',
    mode: null,
    target: '[data-help-id="sales-revenue"]',
    title: 'Sales Revenue',
    summary: 'Total revised revenue for sold projects.',
    body: 'Revenue is calculated from active sold projects and their revised totals after change orders.',
    manualEquivalent: 'Manual sold revenue total.',
    whyItMatters: 'It shows the sales value feeding production.',
    whatToDo: 'Use it with period and region filters for sales review.',
    tour: 'sales',
    order: 410,
  },
  {
    id: 'sales-projects-sold',
    area: 'sales',
    mode: null,
    target: '[data-help-id="sales-projects-sold"]',
    title: 'Projects Sold',
    summary: 'Number of sold projects in the filter.',
    body: 'Projects Sold counts non-cancelled projects in the current filtered period and region.',
    manualEquivalent: 'Manual project count in the sales report.',
    whyItMatters: 'It separates volume from revenue size.',
    whatToDo: 'Compare this with close rate and average contract.',
    tour: 'sales',
    order: 420,
  },
  {
    id: 'sales-leads-given',
    area: 'sales',
    mode: null,
    target: '[data-help-id="sales-leads-given"]',
    title: 'Leads Given',
    summary: 'Demo lead input by salesperson.',
    body: 'Leads Given is used to calculate close rate and value per lead for sales coaching.',
    manualEquivalent: 'Lead assignment sheet.',
    whyItMatters: 'Lead volume provides context for sales results.',
    whatToDo: 'Review it alongside projects sold and revenue.',
    tour: 'sales',
    order: 430,
  },
  {
    id: 'sales-close-rate',
    area: 'sales',
    mode: null,
    target: '[data-help-id="sales-close-rate"]',
    title: 'Close Rate',
    summary: 'Projects divided by leads.',
    body: 'Close Rate estimates how many assigned leads become sold projects.',
    manualEquivalent: 'Manual close-rate math in sales review.',
    whyItMatters: 'It supports coaching and conversion review.',
    whatToDo: 'Use it with value per lead to understand performance.',
    tour: 'sales',
    order: 440,
  },
  {
    id: 'sales-cancel-rate',
    area: 'sales',
    mode: null,
    target: '[data-help-id="sales-cancel-rate"]',
    title: 'Cancel Rate',
    summary: 'Cancelled jobs as a share of sold jobs.',
    body: 'Cancel Rate tracks cancellations so leadership can separate sold work from work that fell out.',
    manualEquivalent: 'Cancelled marks and notes in the book or sales sheet.',
    whyItMatters: 'It keeps revenue and production expectations accurate.',
    whatToDo: 'Open cancelled project files to confirm date and reason.',
    tour: 'sales',
    order: 450,
  },
  {
    id: 'salesperson-performance-table',
    area: 'sales',
    mode: null,
    target: '[data-help-id="salesperson-performance-table"]',
    title: 'Salesperson Performance Table',
    summary: 'Rep-level sales performance.',
    body: 'The table compares each salesperson by projects, cancellations, scopes, revenue, deposits, average contract, leads, close rate, value per lead, and cancel rate.',
    manualEquivalent: 'Sales spreadsheet by rep.',
    whyItMatters: 'It supports coaching conversations with enough context.',
    whatToDo: 'Sort visually by revenue, close rate, value per lead, and cancellations.',
    tour: 'sales',
    order: 460,
  },
  {
    id: 'sales-value-per-lead',
    area: 'sales',
    mode: null,
    target: '[data-help-id="sales-value-per-lead"]',
    title: 'Value Per Lead',
    summary: 'Revenue divided by leads.',
    body: 'Value per lead helps compare how much revenue is generated from the leads assigned to each salesperson. It supports coaching and sales performance review.',
    manualEquivalent: 'Manually comparing leads given to revenue created.',
    whyItMatters: 'It balances close rate with job value.',
    whatToDo: 'Use it to compare rep effectiveness across lead volume.',
    tour: 'sales',
    order: 470,
  },
  {
    id: 'wallboard-main-nav',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="global-main-nav"]',
    title: 'TV Wallboard',
    summary: 'Digital replacement for the physical whiteboard.',
    body: 'TV Wallboard is designed for the big screen. It gives a quick visual snapshot of active work, open alerts, production stages, scheduled scopes, collection needs, sales snapshot, and critical path spotlight.',
    manualEquivalent: 'Physical whiteboard in the office.',
    whyItMatters: 'It makes the current production picture visible to the team.',
    whatToDo: 'Use Display Mode on the office TV.',
    tour: 'full-dashboard',
    order: 130,
  },
  {
    id: 'wallboard-header',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-header"]',
    title: 'TV Wallboard',
    summary: 'Big-screen production view.',
    body: 'The wallboard summarizes active work, open alerts, production columns, bottlenecks, sales snapshot, and critical path items.',
    manualEquivalent: 'Back-room production whiteboard.',
    whyItMatters: 'It provides an at-a-glance operating picture.',
    whatToDo: 'Use the mode toggles to switch between flow and trade views.',
    tour: 'tv-wallboard',
    order: 500,
  },
  {
    id: 'wallboard-production-flow-toggle',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-production-flow-toggle"]',
    title: 'Production Flow',
    summary: 'View work by production stage.',
    body: 'Production Flow groups scopes by where they are in the production process: Needs Measurer, Measure/List Needed, Ready to Order, Ordered/Waiting Materials, Materials In/Ready to Schedule, Scheduled, and Collection/Closeout.',
    manualEquivalent: 'Whiteboard organized by progress/status.',
    whyItMatters: 'It shows where work is collecting in the process.',
    whatToDo: 'Use this mode for production-stage review.',
    tour: 'tv-wallboard',
    order: 510,
  },
  {
    id: 'wallboard-trade-board-toggle',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-trade-board-toggle"]',
    title: 'Trade Board',
    summary: 'View work by trade or product type.',
    body: 'Trade Board groups scopes by work category such as roofs, repairs, siding, trim, gutters, windows, decks, doors, and miscellaneous work.',
    manualEquivalent: 'Whiteboard organized by trade/category.',
    whyItMatters: 'It helps teams review work by crew, trade, or product category.',
    whatToDo: 'Use this mode when assigning trade-specific follow-up.',
    tour: 'tv-wallboard',
    order: 520,
  },
  {
    id: 'wallboard-display-mode',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-display-mode"]',
    title: 'Display Mode',
    summary: 'Full-screen TV view.',
    body: 'Display Mode expands the wallboard for a large screen. Use this for the office TV or video wall. It is meant for viewing, not detailed editing.',
    manualEquivalent: 'Replacing the back-room whiteboard with a TV display.',
    whyItMatters: 'It turns the dashboard into a passive team display.',
    whatToDo: 'Use it when showing the wallboard on a large screen.',
    tour: 'full-dashboard',
    order: 140,
  },
  {
    id: 'wallboard-kpi-active-pipeline',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-kpi-active-pipeline"]',
    title: 'Active Pipeline',
    summary: 'Open production value.',
    body: 'Active Pipeline shows the value of active non-cancelled projects in the current filters.',
    manualEquivalent: 'Manual active job value total.',
    whyItMatters: 'It frames the production workload in dollars.',
    whatToDo: 'Use it as the top-line production value indicator.',
    tour: 'tv-wallboard',
    order: 530,
  },
  {
    id: 'wallboard-kpi-open-alerts',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-kpi-open-alerts"]',
    title: 'Open Alerts',
    summary: 'Bottlenecks requiring action.',
    body: 'Open Alerts counts current bottlenecks visible in the filtered production dataset.',
    manualEquivalent: 'Red marks or circled items on the board.',
    whyItMatters: 'It shows how much work needs immediate attention.',
    whatToDo: 'Review the bottleneck spotlight when this number is high.',
    tour: 'tv-wallboard',
    order: 540,
  },
  {
    id: 'wallboard-kpi-collection-needed',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-kpi-collection-needed"]',
    title: 'Collection Needed',
    summary: 'Completed but not funded.',
    body: 'Collection Needed counts completed projects that still need collection or funding marked complete.',
    manualEquivalent: 'Collection follow-up notes.',
    whyItMatters: 'Completed work is not fully closed until funding is handled.',
    whatToDo: 'Open the project file and mark Collected/Funded when complete.',
    tour: 'tv-wallboard',
    order: 550,
  },
  {
    id: 'wallboard-status-columns',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-status-columns"]',
    title: 'Status Columns',
    summary: 'Scopes grouped by status or trade.',
    body: 'The main wallboard columns show where each active scope sits in the production flow or trade board.',
    manualEquivalent: 'Whiteboard columns and job cards.',
    whyItMatters: 'It makes overloaded stages easy to see.',
    whatToDo: 'Scan for urgent red cards and older active scopes.',
    tour: 'tv-wallboard',
    order: 560,
  },
  {
    id: 'wallboard-bottleneck-spotlight',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-bottleneck-spotlight"]',
    title: 'Bottleneck Spotlight',
    summary: 'Most important stuck items.',
    body: 'The spotlight calls out bottleneck groups with affected jobs and oldest stuck ages.',
    manualEquivalent: 'Most urgent board issues called out in a meeting.',
    whyItMatters: 'It keeps the team focused on the biggest production risks.',
    whatToDo: 'Use it to decide what needs follow-up today.',
    tour: 'tv-wallboard',
    order: 570,
  },
  {
    id: 'wallboard-sales-snapshot',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-sales-snapshot"]',
    title: 'Sales Snapshot',
    summary: 'Sales context on the wallboard.',
    body: 'Sales Snapshot brings current sales revenue, projects, leads, close rate, cancellation rate, and top rep into the wallboard.',
    manualEquivalent: 'Sales meeting notes beside production review.',
    whyItMatters: 'It connects incoming work to production capacity.',
    whatToDo: 'Review it alongside active pipeline.',
    tour: 'tv-wallboard',
    order: 580,
  },
  {
    id: 'wallboard-critical-path-spotlight',
    area: 'wallboard',
    mode: null,
    target: '[data-help-id="wallboard-critical-path-spotlight"]',
    title: 'Critical Path Spotlight',
    summary: 'High-priority critical path items.',
    body: 'This section surfaces decisions, collection issues, cancellations, and scope alerts that deserve leadership attention.',
    manualEquivalent: 'Critical items from the weekly book review.',
    whyItMatters: 'It carries meeting priorities onto the wallboard.',
    whatToDo: 'Review these items during daily or weekly production check-ins.',
    tour: 'tv-wallboard',
    order: 590,
  },
  {
    id: 'modal-project-file',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-project-file"]',
    title: 'Project File',
    summary: 'The editable record for a customer/job.',
    body: 'The project file contains the details that drive all dashboard views: customer information, sales data, intake checklist, scopes, measurement dates, material dates, scheduling, financials, permits, notes, change orders, collection, and cancellation details.',
    manualEquivalent: 'Physical customer file, Critical Path Book entry, notes, and board updates.',
    whyItMatters: 'Every dashboard view is generated from project file data.',
    whatToDo: 'Keep this record current as the job moves forward.',
    tour: 'project-file',
    order: 600,
  },
  {
    id: 'modal-overview-tab',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-overview-tab"]',
    title: 'Overview Tab',
    summary: 'Customer, admin, permits, and notes.',
    body: 'The Overview tab captures customer details, sales/admin fields, permit tracking, intake checklist, meeting notes, and general notes.',
    manualEquivalent: 'Front page of the physical customer file.',
    whyItMatters: 'These fields give context to production and sales views.',
    whatToDo: 'Keep customer and administrative details complete.',
    tour: 'project-file',
    order: 610,
  },
  {
    id: 'modal-intake-checklist',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-intake-checklist"]',
    title: 'Intake Checklist',
    summary: 'Confirm the job setup steps.',
    body: 'The checklist tracks contract receipt, JobNimbus upload, estimate approval, budget creation, invoice creation, and physical folder setup.',
    manualEquivalent: 'Office intake checklist.',
    whyItMatters: 'It prevents new jobs from missing setup steps.',
    whatToDo: 'Check each item as it is completed.',
    tour: 'project-file',
    order: 620,
  },
  {
    id: 'modal-permit-tracking',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-permit-tracking"]',
    title: 'Permit Tracking',
    summary: 'Track required permits and approvals.',
    body: 'Permit fields capture whether a permit is required, the permit type, submitted date, approved date, and notes.',
    manualEquivalent: 'Permit notes in the customer file.',
    whyItMatters: 'Permit delays can block scheduling and production.',
    whatToDo: 'Update submitted and approved dates as they happen.',
    tour: 'project-file',
    order: 630,
  },
  {
    id: 'modal-meeting-notes',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-meeting-notes"]',
    title: 'Meeting Notes',
    summary: 'Decision needed for the weekly sync.',
    body: 'Meeting Notes feed the Meeting View so leadership can see what decision is needed for a job.',
    manualEquivalent: 'Weekly critical path meeting notes.',
    whyItMatters: 'Decision notes keep blockers from getting lost.',
    whatToDo: 'Write the specific decision or leadership question.',
    tour: 'project-file',
    order: 640,
  },
  {
    id: 'modal-general-notes',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-general-notes"]',
    title: 'General Notes',
    summary: 'Customer, supplier, permit, or production notes.',
    body: 'General Notes capture useful context that does not belong in a specific date or financial field.',
    manualEquivalent: 'Notes in the customer folder.',
    whyItMatters: 'They preserve context for anyone opening the file later.',
    whatToDo: 'Keep notes concise and action-oriented.',
    tour: 'project-file',
    order: 650,
  },
  {
    id: 'modal-scopes-tab',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-scopes-tab"]',
    title: 'Work Scopes Tab',
    summary: 'Each trade or product under the job.',
    body: 'Scopes split one customer job into the specific work categories being sold and produced. Each scope has its own measurement, material, schedule, crew, notes, and specs.',
    manualEquivalent: 'Separate book lines or notes for each work category.',
    whyItMatters: 'Scope-level dates drive bottlenecks and the wallboard.',
    whatToDo: 'Add or edit scopes whenever a job has multiple work categories.',
    tour: 'project-file',
    order: 660,
  },
  {
    id: 'modal-scope-measurement-fields',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-scope-measurement-fields"]',
    title: 'Measurement Fields',
    summary: 'Track sold-to-measured progress.',
    body: 'Measurement fields capture measurer, measure requested, measure done, material list received, order date, vendor, and material ETA.',
    manualEquivalent: 'Measurement and ordering columns in the book.',
    whyItMatters: 'These fields clear measurement bottlenecks and move work toward ordering.',
    whatToDo: 'Update these dates as measurement and ordering steps are completed.',
    tour: 'project-file',
    order: 670,
  },
  {
    id: 'modal-scope-production-schedule',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-scope-production-schedule"]',
    title: 'Production Schedule',
    summary: 'Track materials, schedule, and completion.',
    body: 'Production schedule fields capture materials in, scheduled install, and completion date.',
    manualEquivalent: 'Scheduling and completion columns in the book and whiteboard.',
    whyItMatters: 'These fields move scopes across the wallboard columns.',
    whatToDo: 'Update each date as the scope progresses.',
    tour: 'project-file',
    order: 680,
  },
  {
    id: 'modal-scope-work-order-specs',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-scope-work-order-specs"]',
    title: 'Work Order Specs',
    summary: 'Detailed installation/order information.',
    body: 'Specs capture the details needed to order materials and communicate with subcontractors, such as color, size, window style, grid, trim, material type, or other product details.',
    manualEquivalent: 'Work order details and notes needed before ordering materials.',
    whyItMatters: 'Good specs reduce ordering mistakes and crew confusion.',
    whatToDo: 'Add the details needed for ordering and installation.',
    tour: 'project-file',
    order: 690,
  },
  {
    id: 'modal-financials-tab',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-financials-tab"]',
    title: 'Financials Tab',
    summary: 'Contract, deposit, changes, collection, and cancellation.',
    body: 'Financials track the original contract, deposit, revised total, change orders, collected/funded status, thank-you sent, and cancellation fields.',
    manualEquivalent: 'Financial notes in the job file and sales sheet.',
    whyItMatters: 'Financial fields feed pipeline, sales, and collection reporting.',
    whatToDo: 'Update financial and cancellation details as they change.',
    tour: 'project-file',
    order: 700,
  },
  {
    id: 'modal-financial-change-orders',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-financial-change-orders"]',
    title: 'Change Orders',
    summary: 'Adjust the original contract amount.',
    body: 'Use change orders when the final job value changes because of bad wood, added work, or other approved changes. The revised total updates the dashboard numbers.',
    manualEquivalent: 'Updating the book or spreadsheet when the original contract price changes.',
    whyItMatters: 'Accurate revised totals keep sales and pipeline numbers honest.',
    whatToDo: 'Add a dated change order with a clear description and amount.',
    tour: 'project-file',
    order: 710,
  },
  {
    id: 'modal-collected-funded',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-collected-funded"]',
    title: 'Collected / Funded',
    summary: 'Mark completed jobs as funded.',
    body: 'Collected/Funded confirms that completed work has been financially closed out.',
    manualEquivalent: 'Collection follow-up in the office.',
    whyItMatters: 'It clears collection alerts and keeps closeout accurate.',
    whatToDo: 'Mark it when funding or collection is complete.',
    tour: 'project-file',
    order: 720,
  },
  {
    id: 'modal-cancellation-fields',
    area: 'modal',
    mode: null,
    target: '[data-help-id="modal-cancellation-fields"]',
    title: 'Cancellation Date and Reason',
    summary: 'Track cancelled jobs clearly.',
    body: 'If a job cancels, record the cancellation date and reason. This supports accurate cancellation rate tracking and keeps cancelled jobs from being confused with active work.',
    manualEquivalent: 'Marking a job cancelled in the book and retaining a reason for sales/operations review.',
    whyItMatters: 'Cancellation reporting is only useful when reason and date are recorded.',
    whatToDo: 'Check Cancelled, then enter the cancellation date and reason.',
    tour: 'project-file',
    order: 730,
  },
];

export const helpById = helpItems.reduce((acc, item) => {
  acc[item.id] = item;
  return acc;
}, {});

export const manualProcessMap = [
  { manual: 'Critical Path Book', digital: 'Production > Book' },
  { manual: 'Weekly Critical Path Meeting', digital: 'Production > Meeting' },
  { manual: 'Physical Whiteboard', digital: 'TV Wallboard' },
  { manual: 'Measuring follow-up', digital: 'Bottlenecks > Measurement' },
  { manual: 'Sales spreadsheet / manual totals', digital: 'Sales' },
  { manual: 'Customer/job folder', digital: 'Production > Customer / Open File' },
];

export const fieldGuideItems = [
  helpById['modal-project-file'],
  helpById['modal-scopes-tab'],
  helpById['modal-scope-work-order-specs'],
  helpById['modal-financial-change-orders'],
  helpById['modal-cancellation-fields'],
  helpById['bottleneck-days-stuck'],
  helpById['sales-value-per-lead'],
].filter(Boolean);

export const getHelpItemsForScreen = (area, mode) =>
  helpItems
    .filter((item) => item.area === 'global' || item.area === area || item.area === 'modal')
    .filter((item) => item.area !== area || !item.mode || !mode || item.mode === mode)
    .sort((a, b) => a.order - b.order);

export const getTourItems = (tour = 'full-dashboard') =>
  helpItems
    .filter((item) => item.tour === tour || (tour === 'full-dashboard' && item.tour === 'full-dashboard'))
    .sort((a, b) => a.order - b.order);
