import { USER_ROLE, USER_STATUS } from '../domain/enums';

export const CAPABILITY = Object.freeze({
  VIEW_DASHBOARD: 'viewDashboard',
  VIEW_WALLBOARD: 'viewWallboard',
  MANAGE_USERS: 'manageUsers',
  MANAGE_BACKEND: 'manageBackend',
  MANAGE_BUSINESS_DATA: 'manageBusinessData',
  MANAGE_SALES_DATA: 'manageSalesData',
  MANAGE_PRODUCTION_DATA: 'manageProductionData',
  MANAGE_FINANCIAL_DATA: 'manageFinancialData',
  CREATE_PROJECTS: 'createProjects',
  IMPORT_EXPORT: 'importExport',
  RESET_DATA: 'resetData',
  LEGACY_FULL_WRITE: 'legacyFullWrite',
  BACKEND_ADMINISTRATION: 'backendAdministration',
  READ_ONLY: 'readOnly',
  WALLBOARD_ONLY: 'wallboardOnly',
});

const roleCapabilities = {
  [USER_ROLE.OWNER]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: true,
    manageBackend: true,
    manageBusinessData: true,
    manageSalesData: true,
    manageProductionData: true,
    manageFinancialData: true,
    createProjects: true,
    importExport: true,
    resetData: true,
    legacyFullWrite: true,
    backendAdministration: true,
    readOnly: false,
    wallboardOnly: false,
  },
  [USER_ROLE.BUSINESS_ADMIN]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: true,
    manageBackend: true,
    manageBusinessData: true,
    manageSalesData: true,
    manageProductionData: true,
    manageFinancialData: true,
    createProjects: true,
    importExport: true,
    resetData: false,
    legacyFullWrite: true,
    backendAdministration: true,
    readOnly: false,
    wallboardOnly: false,
  },
  [USER_ROLE.OPERATIONS_ADMIN]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: false,
    manageBackend: false,
    manageBusinessData: true,
    manageSalesData: true,
    manageProductionData: true,
    manageFinancialData: true,
    createProjects: true,
    importExport: false,
    resetData: false,
    legacyFullWrite: true,
    backendAdministration: false,
    readOnly: false,
    wallboardOnly: false,
  },
  [USER_ROLE.SALES_MANAGER]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: false,
    manageBackend: false,
    manageBusinessData: false,
    manageSalesData: true,
    manageProductionData: false,
    manageFinancialData: false,
    createProjects: false,
    importExport: false,
    resetData: false,
    legacyFullWrite: false,
    backendAdministration: false,
    readOnly: false,
    wallboardOnly: false,
  },
  [USER_ROLE.SALESPERSON]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: false,
    manageBackend: false,
    manageBusinessData: false,
    manageSalesData: false,
    manageProductionData: false,
    manageFinancialData: false,
    createProjects: false,
    importExport: false,
    resetData: false,
    legacyFullWrite: false,
    backendAdministration: false,
    readOnly: true,
    wallboardOnly: false,
  },
  [USER_ROLE.PRODUCTION_MANAGER]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: false,
    manageBackend: false,
    manageBusinessData: false,
    manageSalesData: false,
    manageProductionData: true,
    manageFinancialData: false,
    createProjects: false,
    importExport: false,
    resetData: false,
    legacyFullWrite: false,
    backendAdministration: false,
    readOnly: false,
    wallboardOnly: false,
  },
  [USER_ROLE.VIEWER]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: false,
    manageBackend: false,
    manageBusinessData: false,
    manageSalesData: false,
    manageProductionData: false,
    manageFinancialData: false,
    createProjects: false,
    importExport: false,
    resetData: false,
    legacyFullWrite: false,
    backendAdministration: false,
    readOnly: true,
    wallboardOnly: false,
  },
  [USER_ROLE.WALLBOARD]: {
    viewDashboard: false,
    viewWallboard: true,
    manageUsers: false,
    manageBackend: false,
    manageBusinessData: false,
    manageSalesData: false,
    manageProductionData: false,
    manageFinancialData: false,
    createProjects: false,
    importExport: false,
    resetData: false,
    legacyFullWrite: false,
    backendAdministration: false,
    readOnly: true,
    wallboardOnly: true,
  },
  [USER_ROLE.DEVELOPER_SUPPORT]: {
    viewDashboard: true,
    viewWallboard: true,
    manageUsers: false,
    manageBackend: false,
    manageBusinessData: false,
    manageSalesData: false,
    manageProductionData: false,
    manageFinancialData: false,
    createProjects: false,
    importExport: false,
    resetData: false,
    legacyFullWrite: false,
    backendAdministration: false,
    readOnly: true,
    wallboardOnly: false,
  },
};

const denied = Object.freeze({
  viewDashboard: false,
  viewWallboard: false,
  manageUsers: false,
  manageBackend: false,
  manageBusinessData: false,
  manageSalesData: false,
  manageProductionData: false,
  manageFinancialData: false,
  createProjects: false,
  importExport: false,
  resetData: false,
  legacyFullWrite: false,
  backendAdministration: false,
  readOnly: true,
  wallboardOnly: false,
});

export const getRoleCapabilities = (role) => ({
  ...denied,
  ...(roleCapabilities[role] || {}),
});

export const mergeServerCapabilities = (role, serverCapabilities = {}) => ({
  ...getRoleCapabilities(role),
  ...serverCapabilities,
});

export const hasCapability = (profile, capability) => Boolean(
  profile?.status === USER_STATUS.ACTIVE
  && profile?.capabilities?.[capability],
);

export const ROLE_LABELS = Object.freeze({
  [USER_ROLE.OWNER]: 'Owner',
  [USER_ROLE.BUSINESS_ADMIN]: 'Business Administrator',
  [USER_ROLE.OPERATIONS_ADMIN]: 'Operations Administrator',
  [USER_ROLE.SALES_MANAGER]: 'Sales Manager',
  [USER_ROLE.SALESPERSON]: 'Salesperson',
  [USER_ROLE.PRODUCTION_MANAGER]: 'Production Manager',
  [USER_ROLE.VIEWER]: 'Viewer',
  [USER_ROLE.WALLBOARD]: 'Wallboard',
  [USER_ROLE.DEVELOPER_SUPPORT]: 'Developer Support',
});

export const ROLE_DESCRIPTIONS = Object.freeze({
  [USER_ROLE.OWNER]: 'Full business, user, backend, financial, sales, and production authority.',
  [USER_ROLE.BUSINESS_ADMIN]: 'Broad administration without authority to assign or remove the owner role.',
  [USER_ROLE.OPERATIONS_ADMIN]: 'Operational, sales, production, and financial management without user administration.',
  [USER_ROLE.SALES_MANAGER]: 'Customer and sales-field management. Production and financial edits are blocked.',
  [USER_ROLE.SALESPERSON]: 'Read access in the current legacy interface. Ownership-scoped editing follows normalized screens.',
  [USER_ROLE.PRODUCTION_MANAGER]: 'Work-scope, material, schedule, crew, permit, and production-note management.',
  [USER_ROLE.VIEWER]: 'Read-only operator-dashboard access.',
  [USER_ROLE.WALLBOARD]: 'Read-only TV Wallboard display access.',
  [USER_ROLE.DEVELOPER_SUPPORT]: 'Read-only support access without business-data or backend-administration authority.',
});

export const ROLE_OPTIONS = Object.entries(ROLE_LABELS).map(([value, label]) => ({
  value,
  label,
  description: ROLE_DESCRIPTIONS[value],
}));

export const getAssignableRoles = (actorRole) => ROLE_OPTIONS.filter(
  (option) => actorRole === USER_ROLE.OWNER || option.value !== USER_ROLE.OWNER,
);

export const createLocalOwnerProfile = () => ({
  id: 'USR-LOCAL-OWNER',
  authUserId: null,
  displayName: 'Local Prototype Administrator',
  email: '',
  role: USER_ROLE.OWNER,
  status: USER_STATUS.ACTIVE,
  regionAccess: ['Virginia', 'Carolina'],
  localMode: true,
  capabilities: getRoleCapabilities(USER_ROLE.OWNER),
});
